spring:
  application: 
   name: discoxp
  datasource:
    url: jdbc:mysql://localhost:3306/db_discoxp
    username: root
    password: "minhasenha"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

